version: "3.7"
services:
  rabbitmq:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rabittmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    hostname: stats
    volumes:
      - ./data:/var/lib/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: proyectomonitoreo
      RABBITMQ_DEFAULT_PASS: grado2021
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 0.5
    networks:
      rabbitmq_net:
        aliases:
          - rabbitmq_host
volumes:
  data: {}
networks:
  rabbitmq_net:
    name: rabbitmq_network
    driver: bridge